<style TYPE="text/css">
    <!--

       A.menulink {color: white; text-decoration: none;}
       
       A.menulink:hover {color: yellow; text-decoration: underline;}

       A.contentlink 
                {
                  background-color: white; 
                  color: rgb(2,85,137);
                  text-decoration: underline;
                 }
       
       A.contentlink:hover 
                {
                  background-color: rgb(240,240,225);
                  color: rgb(0,128,64); 
                  text-decoration: underline;
                 }

       A.submenulink {color: black; text-decoration: none;}

       A.submenulink:hover {color: Blue; text-decoration: underline;}

    -->
 </style>


